### ISSUE TITLE
Rust documentation broken

### ISSUE THREAD

**Issue by oscartbeaumont** [conradludgate/pasta-tokens#1]
Hey,
The library looks awesome but right now `docs.rs` is hitting errors while building the documentation for this repo. Would be awesome to get it ironed out so that it's easier to explore the API surface.

For now, I am just gonna use `cargo doc` locally.

[crates.io page](https://docs.rs/crate/pasta-tokens/0.1.0-rc.7), [Build Log](https://docs.rs/crate/pasta-tokens/0.1.0-rc.7/builds)

Thanks!

**Comment by conradludgate** [comment]
Fixed now. Accidental breaking change in a dep + docs rebuild
